# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    # image: postgres:9.6.17
    image: postgres:9.5
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./BKP.20180328:/var/lib/postgresql/data

#  postgres_data:
#    volumes:
#      - /home/rabbuhl/dev/database/BKP.20180328
